# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-11-15 16:10
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdviseSetup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_code', models.CharField(choices=[('0050', '元大台灣50(0050)'), ('2430', '燦坤(2430)')], max_length=4)),
                ('position', models.CharField(choices=[('principal', '本金'), ('stock', '持有股數')], max_length=4)),
                ('principal', models.IntegerField()),
                ('initialStockHold', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField(default=0)),
                ('action', models.CharField(choices=[('等待', '等待'), ('持有', '持有'), ('買入', '買入'), ('賣出', '賣出')], max_length=2)),
                ('position_after_action', models.CharField(choices=[('現金', '現金'), ('股票', '股票')], max_length=1)),
                ('last_trading_price_after_action', models.FloatField(null=True)),
                ('rate_of_return_after_action', models.FloatField()),
                ('cash_held_after_action', models.FloatField(default=0)),
                ('number_of_shares_held_after_action', models.FloatField(default=0)),
            ],
            options={
                'db_table': 'history',
            },
        ),
        migrations.CreateModel(
            name='RankingHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('final_rate_of_return', models.FloatField()),
            ],
            options={
                'db_table': 'RankingHistory',
            },
        ),
        migrations.CreateModel(
            name='Setup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initial_transaction_date', models.DateField()),
                ('playing_duration', models.IntegerField(choices=[(60, '60個交易日(三個月)'), (240, '240個交易日(一年)')])),
                ('principal', models.IntegerField()),
                ('transaction_cost_rate', models.FloatField(choices=[(0.001425, '股票買賣現行手續費率(0.1425%)'), (0, '無')])),
            ],
            options={
                'db_table': 'setup',
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30)),
                ('date', models.DateField()),
                ('volumn', models.IntegerField()),
                ('turnover', models.IntegerField()),
                ('opening_price', models.FloatField()),
                ('high', models.FloatField()),
                ('low', models.FloatField()),
                ('closing_price', models.FloatField()),
                ('spread', models.FloatField()),
                ('transaction_number', models.IntegerField()),
            ],
            options={
                'db_table': 'stock',
            },
        ),
        migrations.CreateModel(
            name='StockCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'stockCode',
            },
        ),
        migrations.AddField(
            model_name='setup',
            name='stock_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TradingGame.StockCode'),
        ),
        migrations.AddField(
            model_name='setup',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rankinghistory',
            name='setup',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TradingGame.Setup'),
        ),
        migrations.AddField(
            model_name='history',
            name='setup',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TradingGame.Setup'),
        ),
    ]
