# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-09-08 08:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_before_action', models.CharField(choices=[('0', '現金'), ('1', '股票')], max_length=1)),
                ('rate_of_return_before_action', models.FloatField()),
                ('action', models.CharField(choices=[('0', '等待or持有'), ('1', '買or賣')], max_length=1)),
            ],
            options={
                'db_table': 'history',
            },
        ),
        migrations.CreateModel(
            name='Setup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_code', models.CharField(choices=[('0050', '元大台灣50'), ('2430', '燦坤')], max_length=4)),
                ('initial_transaction_date', models.DateField()),
                ('playing_duration', models.IntegerField()),
                ('principal', models.IntegerField()),
                ('transaction_cost_rate', models.FloatField()),
            ],
            options={
                'db_table': 'setup',
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30)),
                ('date', models.DateField()),
                ('volumn', models.IntegerField()),
                ('turnover', models.IntegerField()),
                ('opening_price', models.FloatField()),
                ('high', models.FloatField()),
                ('low', models.FloatField()),
                ('closeing_price', models.FloatField()),
                ('spread', models.FloatField()),
                ('transaction_number', models.IntegerField()),
            ],
            options={
                'db_table': 'stock',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('last_modify_date', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.AddField(
            model_name='setup',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TradingGame.User'),
        ),
        migrations.AddField(
            model_name='history',
            name='stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='TradingGame.Stock'),
        ),
        migrations.AddField(
            model_name='history',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TradingGame.User'),
        ),
    ]
