# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-10-27 22:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TradingGame', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='action',
            field=models.CharField(choices=[('等待', '等待'), ('持有', '持有'), ('買入', '買入'), ('賣出', '賣出')], max_length=2),
        ),
    ]
