# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-10-28 12:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TradingGame', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RankingHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('final_rate_of_return', models.FloatField()),
                ('setup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TradingGame.Setup')),
            ],
        ),
    ]
