# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-09-22 03:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TradingGame', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock',
            old_name='closeing_price',
            new_name='closing_price',
        ),
    ]
