# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-10-14 14:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TradingGame', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='closing_price',
            field=models.FloatField(null=True),
        ),
    ]
