# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-09-02 13:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TradingGame', '0002_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField()),
                ('date', models.DateField()),
                ('volumn', models.IntegerField()),
                ('turnover', models.IntegerField()),
                ('opening_price', models.IntegerField()),
                ('high', models.FloatField()),
                ('row', models.FloatField()),
                ('closeing_price', models.FloatField()),
                ('spread', models.FloatField()),
                ('transaction_number', models.IntegerField()),
            ],
            options={
                'db_table': 'stock',
            },
        ),
    ]
