# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-10-28 12:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TradingGame', '0002_rankinghistory'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='rankinghistory',
            table='RankingHistory',
        ),
    ]
