# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-09-02 13:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TradingGame', '0003_stock'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock',
            old_name='row',
            new_name='low',
        ),
        migrations.AlterField(
            model_name='stock',
            name='code',
            field=models.CharField(max_length=30),
        ),
    ]
