# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-10-14 15:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TradingGame', '0003_auto_20191014_2218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='last_trading_price_after_action',
            field=models.FloatField(null=True),
        ),
    ]
