# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-09-27 15:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TradingGame', '0003_coffee'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Coffee',
        ),
    ]
