# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-09-02 13:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TradingGame', '0004_auto_20190902_2122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='opening_price',
            field=models.FloatField(),
        ),
    ]
