# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-10-13 13:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TradingGame', '0006_auto_20191009_1821'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='history',
            name='stock',
        ),
        migrations.RemoveField(
            model_name='history',
            name='user',
        ),
        migrations.AddField(
            model_name='history',
            name='day',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='history',
            name='setup',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='TradingGame.Setup'),
            preserve_default=False,
        ),
    ]
